AutoMQ/elastic-stream

Cargo.toml
fix https://github.com/AutoMQ/elastic-stream/issues/192
=> fix(data-node): enable nightly feature of crc32fast

Cargo.lock, components/observation/Cargo.toml, components/observation/src/metrics/sys_metrics.rs, components/util/Cargo.toml, components/util/src/metrics/process_linux.rs, components/util/src/metrics/threads_linux.rs
=> fix(observation): Replace procinfo with procfs

components/client/src/composite_session.rs
=> fix(observation): Broadcast metrics to all pm nodes

sdks/rust/src/bindings/java.rs
Fix  #273, add some help funtion and remove unnecessary unsafe
=> fix(frontend): Add error handlings and remove unnecessary unsafe

components/client/src/client.rs, components/client/src/composite_session.rs, components/replication/src/stream_manager/replication_range.rs, components/replication/src/stream_manager/replication_stream.rs, etc/data-node-log.yaml
Fix https://github.com/AutoMQ/elastic-stream/issues/317
=> fix(session): retry describe pm cluster

sdks/frontend-rs/Cargo.toml
=> fix(frontend): Add cdylib to frontend-rs crate type

sdks/frontend-java/client/src/main/java/com/automq/elasticstream/client/DefaultStream.java, sdks/frontend-java/client/src/main/java/com/automq/elasticstream/client/jni/Stream.java, sdks/frontend-rs/src/bindings/cmd.rs, sdks/frontend-rs/src/bindings/java.rs, sdks/frontend-rs/src/stream.rs
=> fix(frontend): Add async close stream method

sdks/frontend-java/client/src/main/java/com/automq/elasticstream/client/DefaultStream.java, sdks/frontend-java/client/src/main/java/com/automq/elasticstream/client/jni/Stream.java
=> fix(frontend): Fix frontend read unify to readOffset

components/model/src/record/flat_record.rs, components/replication/src/stream_manager/replication_stream.rs, sdks/frontend-java/client/src/test/java/com/automq/elasticstream/client/FlatRecordBatchCodecTest.java, sdks/frontend-java/examples/pom.xml, sdks/frontend-java/examples/src/main/java/com/automq/elasticstream/client/examples/Main.java, sdks/frontend-rs/examples/main.rs
also fix https://github.com/AutoMQ/elastic-stream/issues/358
=> fix(frontend): fix stream fetch when has more than one range

components/model/src/range/mod.rs, data-node/src/handler/append.rs, data-node/src/handler/fetch.rs, data-node/src/stream_manager/stream.rs, data-node/src/stream_manager/stream_manager.rs, sdks/frontend-rs/examples/main.rs
Fix https://github.com/AutoMQ/elastic-stream/issues/362
=> fix(datanode): fix data-node get wrong range cause fetch fail

components/replication/src/stream_manager/replication_range.rs
fix https://github.com/AutoMQ/elastic-stream/issues/365
=> fix(frontend): fix range drop before replicas seal complete

sdks/frontend-rs/src/bindings/java.rs
=> fix(frontend): Add jclass cache

components/replication/src/stream/replication_stream.rs, components/replication/src/stream/replicator.rs
fix https://github.com/AutoMQ/elastic-stream/issues/431
=> fix(replication): set replicator init confirm offset

components/observation/src/metrics/store_metrics.rs, components/observation/src/metrics/uring_metrics.rs
=> fix(observation): Fix subtract overflow panic

.vscode/settings.json, components/client/src/session.rs, components/test-util/src/test_util/mod.rs, components/transport/src/connection.rs, components/transport/src/lib.rs, components/transport/src/sync.rs, components/transport/src/write_task.rs, data-node/src/session.rs
via MPSC channel, as a write buffer
=> fix(transport): Serialize concurrent writes of frames from coroutines 

.github/workflows/data_node_release.yml, dist/data-node/DEBIAN/control, dist/data-node/DEBIAN/postinst, dist/data-node/etc/data-node/.gitignore, dist/data-node/usr/local/bin/.gitignore, scripts/package_deb.sh
data-node-v{major}.{minor}.{patch}
=> feat(ci): Release data-node on tagging

Cargo.toml
Filter log statements at compile time.
=> fix(log): Filter some log statements at compile time

.github/workflows/java_build.yml, scripts/install_deps.sh, sdks/build.sh, sdks/frontend-java/client/src/main/java/com/automq/elasticstream/client/jni/Frontend.java, sdks/frontend-java/client/src/test/java/com/automq/elasticstream/client/jni/FrontendTest.java, sdks/frontend-rs/src/bindings/java.rs
Add unit test for Frontend#{allocateDirect, freeMemory}
Remove rocksdb.deb after installation
=> fix(frontend): Expose API to allocate / deallocate memory

components/config/src/lib.rs, components/store/src/io/segment.rs, components/store/src/io/wal.rs, etc/data-node.yaml
=> feat(store): Support recycling segment files

Cargo.lock, Cargo.toml, components/config/Cargo.toml, components/config/src/error.rs, components/config/src/lib.rs, components/store/src/index/driver.rs, components/store/src/index/indexer.rs, components/store/src/io/uring.rs, components/store/src/store/elastic_store.rs, data-node/src/server.rs, docs/cpu_set.md, etc/data-node.yaml, scripts/install_deps.sh, sdks/frontend-rs/examples/main.rs
fix https://github.com/AutoMQ/elastic-stream/issues/585
=> feat(data-node): Optimize CPU affinity

components/store/src/io/buf/aligned_buf_writer.rs
This reverts commit 8a003e194bf8973d9173a20a8a027aac0b32feed.
=> fix(io): Revert "feat(io): Tune optimal IO size (#579)"

docs/why-rust.md
=> feat(doc): Explain decision of choosing rust in performance critical components

Cargo.lock, components/config/src/lib.rs, components/util/Cargo.toml, components/util/src/bin/metrics_client.rs, components/util/src/metrics/mod.rs, etc/range-server.yaml, range-server/src/worker.rs
=> fix(observation): Make metrics server port configurable

components/store/src/io/wal.rs
The execute permission of segment file is unnecessary
=> fix(store): Remove the execute permission of segment file

README.md
Close #624 . My understanding might not be accurate, and I would be delighted to receive advice and guidance from other developers 😄
=> docs(README): Keep the 'How to Build' section up-to-date

dist/docker/Dockerfile.pd, dist/docker/Dockerfile.rs, dist/docker/build.sh, dist/docker/config/config.yaml, dist/docker/config/range-server.yaml, dist/docker/docker-compose.yaml
=> feat(cicd): Facilitate quick launch of a standalone cluster
